---
- name: Check if runnning on a supported platform.
  assert:
    that: "{{ ansible_distribution|lower == 'debian' }}"
    quiet: true
    fail_msg: This role does not support {{ ansible_distribution }}.

- name: Execute distribution dependent setup.
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

- name: Update configuration file.
  template:
    src: templates/mpd.conf.j2
    dest: /etc/mpd.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart the mpd service.

- name: Enable the mpd service.
  systemd:
    name: mpd.service
    state: started
    enabled: true
  when: mpd_service

- name: Disable the mpd service.
  systemd:
    name: mpd.service
    state: started
    enabled: true
  when: not mpd_service
